### ISSUE TITLE
Make it so everyone can see the store widget.

### ISSUE THREAD

**Issue by boopdoop1532** [CqldFire/namelessmc-products#10]
### Product

Cobalt

### Describe the feature

At the moment right now, only guests can see the store widget. I personally would want everyone to see the store widget and It would be a nice feature if people as well as guests would be able to see the store widget on the website by default or make it a toggleable feature on cobalt. Reason being, is that it would be a nice little feature to add and I feel like it would really be appreciated by the customers of Cobalt :)

**Comment by CqldFire** [comment]
will be added in #5
